=== rossvideo/Catena/schema/catena.device_schema.json
{
  "$id": "catena.device_schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Catena Device Model Schema",
  "description": "Intended to assist humans to author Catena device models as JSON files as some IDEs can use schemata such as this one to lint models.",
  "type": "object",
  "properties": {
    "slot": {
      "$ref": "#/$defs/slot"
    },
    "detail_level": {
      "$ref": "#/$defs/detail_level"
    },
    "multi_set_enabled": {
      "title": "Multi Set Message Enabled Flag",
      "description": "Enables use of the multi-value message to report multiple parameter changes in one message. Otherwise changes will be reported individually using the value message. Defaults to true.",
      "type": "boolean"
    },
    "subscriptions": {
      "title": "Subscriptions Flag",
      "description": "When true, indicates that the device supports subscription-based access to subsets of parameters.",
      "type": "boolean"
    },
    "constraints": {
      "$ref": "#/$defs/constraint_map"
    },
    "params": {
      "type": "object",
      "patternProperties": {
        "^((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)(\\/((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)){0,31}$": {
          "$ref": "catena.param_schema.json#"
        }
      }
    },
    "commands": {
      "type": "object",
      "patternProperties": {
        "^((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)(\\/((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)){0,31}$": {
          "$ref": "catena.param_schema.json#"
        }
      }
    },
    "access_scopes": {
      "title": "Access Scopes",
      "description": "The access scopes recognised by this device",
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true,
        "maxItems": 5,
        "$comment": "discussion needed on min & max items"
      },
      "additionalItems": false
    },
    "default_scope": {
      "$id": "Default Access Scope",
      "description": "Objects in the model will have this access scope unless overridden explicitly, or implicitly by inheritance",
      "type": "string"
    },
    "language_packs": {
      "$ref": "#/$defs/language_packs",
      "additionalProperties": true,
      "description": "The devices language packs"
    },
    "menu_groups": { "$ref": "#/$defs/menu_groups" }
  },
  "required": ["slot"],
  "additionalProperties": false,
  "$defs": {
    "external_object_payload": {
      "title": "External Object Payload",
      "description": "A payload for an external object",
      "type": "object",
      "properties": {
        "data": { "type": "string" }
      }
    },
    "menu_groups": {
      "title": "Menu Groups",
      "description": "An operationally logical grouping of menus.",
      "type": "object",
      "patternProperties": {
        "^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$": {
          "$ref": "#/$defs/menu_group"
        }
      },
      "additionalProperties": false
    },
    "menu_group": {
      "title": "Menu Group",
      "description": "A group of menus",
      "type": "object",
      "properties": {
        "name": { "$ref": "catena.param_schema.json#/$defs/polyglot_text" },
        "menus": { "$ref": "#/$defs/menus" }
      },
      "additionalProperties": false
    },
    "menus": {
      "title": "Menus",
      "description": "The menus recognised by this device",
      "type": "object",
      "patternProperties": {
        "^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$": {
          "$ref": "#/$defs/menu"
        }
      },
      "additionalProperties": false
    },
    "menu": {
      "title": "Menu",
      "description": "A menu",
      "type": "object",
      "properties": {
        "name": { "$ref": "catena.param_schema.json#/$defs/polyglot_text" },
        "param_oids": { "$ref": "#/$defs/oids_list" },
        "command_oids": { "$ref": "#/$defs/oids_list" },
        "client_hints": { "$ref": "catena.param_schema.json#/$defs/client_hints" },
        "hidden": {
          "type": "boolean",
          "default": false
        },
        "disabled": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "oids_list": {
      "title": "OIDs List",
      "description": "A list of Fully Qualified Object IDs",
      "type": "array",
      "items": { "type": "string", "format": "json-pointer" },
      "additionalItems": false
    },
    "language_pack": {
      "properties": {
        "name": {
          "type": "string"
        },
        "words": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "additionalProperties": true,
      "type": "object",
      "title": "Language Pack",
      "description": "Language Pack A map of string identifiers, e.g. \"greeting\" to strings which are all in the same language."
    },
    "language_packs": {
      "properties": {
        "packs": {
          "additionalProperties": {
            "$ref": "#/$defs/language_pack",
            "additionalProperties": true
          },
          "type": "object"
        }
      },
      "additionalProperties": true,
      "type": "object",
      "title": "Language Packs",
      "description": "Language Packs A map of language identifiers to resource dictionaries or language packs for each language supported. The keys shall be patterned on those defined in https://www.mesaonline.org/language-metadata-table, e.g. \"es\" for Global Spanish. \"es-CO\" for Colombian Spanish. \"pl\" for Jezyk polski"
    },
    "constraint_map": {
      "title": "map of constraints used for top-level shared constraints",
      "description": "Defines the collection of constraints that are able to be shared amongst params or commands within a device.",
      "type": "object",
      "$comment": "patternProperties regex must be same as that defined in oid schema",
      "patternProperties": {
        "(^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$)": {
          "$ref": "catena.param_schema.json#/$defs/constraint"
        }
      },
      "additionalProperties": false
    },
    "slot": {
      "title": "Slot ID",
      "description": "Uniquely identifies the device within the scope of its Catena connection",
      "type": "integer",
      "minimum": 0,
      "maximum": 65535,
      "default": 0
    },
    "slot_list": {
      "title": "Slot List",
      "description": "A list of slot IDs",
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "items": {
        "$ref": "#/$defs/slot"
      },
      "additionalItems": false
    },
    "detail_level": {
      "title": "Level of Detail",
      "description": "The level of detail in device messages and parameter updates. 'full' indicates that all parameters are reported, 'minimal' that only the minimal set is, 'subscription' reports the minimal set plus identified subscribed parameters, 'commands' reports only descriptors for commands and not for parameters, and 'none' indicates that no parameters or commands should be automatically reported by the device (parameter descriptors, command descriptors, and values can still be pulled). ",
      "type": "string",
      "enum": ["FULL", "SUBSCRIPTIONS", "MINIMAL", "COMMANDS", "NONE"],
      "default": "FULL"
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/gRPC/examples/dashboard_audiodeck/device.audiodeck.json
{
  "slot": 0,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "subscriptions": true,
  "detail_level": "FULL",
  "default_scope": "st2138:op",
  "language_packs": {},
  "params": {
    "dashboard_UI": {
      "type": "STRING",
      "minimal_set": true,
      "oid_aliases": ["0xFF0E"],
      "read_only": true,
      "value": { "string_value": "eo://AudioDeck.grid" }
    },
    "dashboard_icon": {
      "type": "STRING",
      "oid_aliases": ["0xFF0C"],
      "read_only": true,
      "value": { "string_value": "eo://catena_logo_16x16.png" }
    },
    "eq": {
      "type": "STRUCT",
      "name": { "display_strings": { "en": "EQ" } },
      "params": {
        "response": {
          "type": "INT32",
          "name": { "display_strings": { "en": "Response" } },
          "access_scope": "st2138:mon",
          "constraint": {
            "type": "INT_RANGE",
            "int32_range": {"min_value": 0, "max_value": 100, "step": 2}
          },
          "widget": "wheel"
        },
        "frequency": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Frequency" } },
          "access_scope": "st2138:op",
          "constraint": {
            "type": "FLOAT_RANGE",
            "float32_range": {"min_value":20, "display_min": 20,  "max_value": 20000, "display_max": 20000}
          },
          "widget": "wheel"
        },
        "gain": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Gain" } },
          "access_scope": "st2138:cfg",
          "constraint": {
            "type": "FLOAT_RANGE",
            "float32_range": {"min_value":0,  "max_value": 10.0, "step": 0.1}
          },
          "widget": "wheel"
        },
        "q_factor": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Q Factor" } },
          "access_scope": "st2138:adm",
          "constraint": {
            "type": "FLOAT_RANGE",
            "float32_range": {"min_value":0,  "max_value": 10.0, "step": 0.1}
          },
          "widget": "wheel"
        }
      }
    },
    "audio_channel": {
      "type": "STRUCT",
      "name": { "display_strings": { "en": "Audio Channel" } },
      "params": {
        "fader": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Fader" } },
          "constraint": {
            "type": "FLOAT_RANGE",
            "float32_range": {"min_value":0,  "max_value": 1.00, "display_min":0, "display_max":1.00, "step": 0.01}
          },
          "precision": 3,
          "widget": "fader"
        },
        "eq_list": {
          "type": "STRUCT_ARRAY",
          "name": { "display_strings": { "en": "EQ List" } },
          "template_oid": "/eq",
          "value": {
            "struct_array_values": {
              "struct_values": [
                {"struct_value": {"fields": {"response": {"int32_value": 0}, "frequency": {"float32_value": 0}, "gain": {"float32_value": 0}, "q_factor": {"float32_value": 0}}}},
                {"struct_value": {"fields": {"response": {"int32_value": 0}, "frequency": {"float32_value": 0}, "gain": {"float32_value": 0}, "q_factor": {"float32_value": 0}}}}
              ]
            }
          }
        }
      }
    },
    "audio_deck": {
      "type": "STRUCT_ARRAY",
      "name": { "display_strings": { "en": "Audio Deck" } },
      "template_oid": "/audio_channel",
      "minimal_set": true,
      "value": {
        "struct_array_values": {
          "struct_values": [
            {"struct_value": {"fields": {"fader": {"float32_value": 0.0}, "eq_list": {"struct_array_values": {"struct_values": [
              {"struct_value": {"fields": {"response": {"int32_value": 10}, "frequency": {"float32_value": 0.8}, "gain": {"float32_value": 2.5}, "q_factor": {"float32_value": 8.4}}}},
              {"struct_value": {"fields": {"response": {"int32_value": 20}, "frequency": {"float32_value": 4.7}, "gain": {"float32_value": 3.7}, "q_factor": {"float32_value": 5.6}}}}
            ]}}}}},
            {"struct_value": {"fields": {"fader": {"float32_value": 0.1}, "eq_list": {"struct_array_values": {"struct_values": [
              {"struct_value": {"fields": {"response": {"int32_value": 30}, "frequency": {"float32_value": 0.8}, "gain": {"float32_value": 2.5}, "q_factor": {"float32_value": 9.3}}}},
              {"struct_value": {"fields": {"response": {"int32_value": 40}, "frequency": {"float32_value": 1.9}, "gain": {"float32_value": 0.5}, "q_factor": {"float32_value": 1.2}}}}
            ]}}}}},
            {"struct_value": {"fields": {"fader": {"float32_value": 0.2}, "eq_list": {"struct_array_values": {"struct_values": [
              {"struct_value": {"fields": {"response": {"int32_value": 50}, "frequency": {"float32_value": 1.1}, "gain": {"float32_value": 3.8}, "q_factor": {"float32_value": 0.9}}}},
              {"struct_value": {"fields": {"response": {"int32_value": 60}, "frequency": {"float32_value": 4.2}, "gain": {"float32_value": 4.6}, "q_factor": {"float32_value": 0.3}}}}
            ]}}}}},
            {"struct_value": {"fields": {"fader": {"float32_value": 0.3}, "eq_list": {"struct_array_values": {"struct_values": [
              {"struct_value": {"fields": {"response": {"int32_value": 70}, "frequency": {"float32_value": 1.4}, "gain": {"float32_value": 4.5}, "q_factor": {"float32_value": 0.1}}}},
              {"struct_value": {"fields": {"response": {"int32_value": 80}, "frequency": {"float32_value": 6.1}, "gain": {"float32_value": 4.8}, "q_factor": {"float32_value": 9.9}}}}
            ]}}}}}
          ]
        }
      }
    },
    "product": {
      "type": "STRUCT",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "Video Player" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING"
        },
        "vendor": {
          "type": "STRING"
        },
        "version": {
          "type": "STRING"
        },
        "catena_sdk": {
          "type": "STRING"
        },
        "catena_sdk_version": {
          "type": "STRING"
        },
        "serial_number": {
          "type": "STRING"
        }
      }
    }
  },
  "commands": {
    "play": {
      "name": {"display_strings": {
        "en": "Play",
        "fr": "Lire",
        "es": "Reproducir",
        "ja": "再生"
      }},
      "type":"EMPTY",
      "widget": "button"
    },
    "pause": {
      "name": {"display_strings": {
        "en": "Pause",
        "fr": "Pause",
        "es": "Pausa",
        "ja": "一時停止"
      }},
      "type":"EMPTY"
    },
    "stop": {
      "name": {"display_strings": {
        "en": "Stop",
        "fr": "Arrêter",
        "es": "Detener",
        "ja": "停止"
      }},
      "type":"EMPTY"
    },
    "rewind": {
      "name": {"display_strings": {
        "en": "Rewind",
        "fr": "Rembobiner",
        "es": "Rebobinar",
        "ja": "巻き戻し"
      }},
      "type": "EMPTY"
    },
    "fast_forward": {
      "name": {"display_strings": {
        "en": "Fast Forward",
        "fr": "Avance rapide",
        "es": "Avance rápido",
        "ja": "早送り"
      }},
      "type": "EMPTY"
    },
    "load": {
      "name": {"display_strings": {
        "en": "Load Video",
        "fr": "Charger la vidéo",
        "es": "Cargar video",
        "ja": "ビデオを読み込む"
      }},
      "widget": "button",
      "type":"STRING"
    },
    "eject": {
      "type":"STRING",
      "name": {"display_strings": {
        "en": "Eject",
        "fr": "Éjecter",
        "es": "Expulsar",
        "ja": "取り出す"
      }},
      "widget": "button"
    },
    "debug_counter": {
      "name": {"display_strings": {
        "en": "Debug Counter",
        "fr": "Compteur de débogage",
        "es": "Contador de depuración",
        "ja": "デバッグカウンター"
      }},
      "type":"INT32",
      "widget": "button",
      "read_only": true, 
      "response": true
    },
    "multi_arg_command": {
      "name": {"display_strings": {
        "en": "Multi-Arg Command",
        "fr": "Commande multi-argument",
        "es": "Comando multi-argumento",
        "ja": "マルチ引数コマンド"
      }},
      "type":"STRUCT",
      "widget": "button",
      "read_only": false,
      "response": true,
      "params": {
        "arg1": {
          "type": "INT32"
        },
        "arg2": {
          "type": "INT32"
        }
      }
    }
  },
  "menu_groups": {
    "status": {
      "name": { "display_strings": {
        "en": "Status",
        "fr": "État",
        "es": "Estado",
        "ja": "ステータス"
      }},
      "menus": {
        "state": {
          "name": { "display_strings": {
            "en": "State",
            "fr": "État",
            "es": "Estado",
            "ja": "状態"
          }},
          "param_oids": ["/state"]
        }
      },
      "order": 0
    },
    "config": {
      "name": { "display_strings": {
        "en": "Configuration",
        "fr": "Configuration",
        "es": "Configuración",
        "ja": "設定"
      }},
      "menus": {
        "commands": {
          "name": { "display_strings": {
            "en": "Commands",
            "fr": "Commandes",
            "es": "Comandos",
            "ja": "コマンド"
          }},
          "param_oids": [],
          "command_oids": ["/play", "/pause", "/stop", "/rewind", "/fast_forward", "/load", "/eject"]
        }
      },
      "order": 1
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/REST/examples/asset_request_REST/device.asset_request.json
{
  "slot": 0,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "subscriptions": true,
  "params": {
    "device_name": {
      "type": "STRING",
      "read_only": true,
      "value": { "string_value": "External Object Request Device" }
    },
    "assets": {
      "type": "STRING_ARRAY",
      "name": { "display_strings": { "en": "Assets", "es": "Assets", "fr": "Assets" } },
      "value": { "string_array_values": { "strings": [] } }
    },
    "product": {
      "type": "STRUCT",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "Asset Request" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING"
        },
        "vendor": {
          "type": "STRING"
        },
        "version": {
          "type": "STRING"
        },
        "catena_sdk": {
          "type": "STRING"
        },
        "catena_sdk_version": {
          "type": "STRING"
        },
        "serial_number": {
          "type": "STRING"
        }
      }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/gRPC/examples/setValueTest/device.setValueTest.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "params": {

    "int_test" : {
      "type": "INT32",
      "value": {"int32_value": 0}
    },

    "float_test" : {
      "type": "FLOAT32",
      "value": {"float32_value": 0}
    },

    "string_test" : {
      "type": "STRING",
      "value": {"string_value": "0"},
      "max_length": 10
    },

    "int_array_test" : {
      "type": "INT32_ARRAY",
      "value": {"int32_array_values": {"ints": [0]}},
      "max_length": 5
    },

    "float_array_test" : {
      "type" : "FLOAT32_ARRAY",
      "value": {"float32_array_values": {"floats": [0]}},
      "max_length": 3
    },

    "string_array_test" : {
      "type" : "STRING_ARRAY",
      "value": {"string_array_values": {"strings": ["0"]}},
      "max_length": 5,
      "total_length": 10
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/gRPC/examples/use_menus/device.use_menus.json
{
  "slot": 0,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "language_packs": {
    "packs": {
      "es": {
        "name": "Spanish",
        "words": {
          "greeting": "Hola",
          "parting": "Adiós"
        }
      },
      "en": {
        "name": "English",
        "words": {
          "greeting": "Hello",
          "parting": "Goodbye"
        }
      },
      "fr": {
        "name": "French",
        "words": {
          "greeting": "Bonjour",
          "parting": "Adieu"
        }
      }
    }
  },
  "menu_groups": {
    "status": {
      "name": { "display_strings": { "en": "status", "es": "estado", "fr": "statut" } },
      "menus": {
        "page_1": {
          "name": { "display_strings": { "en": "Product", "es": "Producto", "fr": "Produit" } },
          "param_oids": ["/product/name", "/product/vendor", "/product/version", "/product/serial_number", "/product/catena_sdk", "/product/catena_sdk_version"]
        },
        "page_2": {
          "name": { "display_strings": { "en": "Page 2", "es": "Página 2", "fr": "Page 2" } },
          "param_oids": ["/offset", "/button", "/counter"]
        }
      },
      "order": 0
    },
    "config": {
      "name": { "display_strings": { "en": "config", "es": "configuración", "fr": "configuration" } },
      "menus": {
        "page_1": {
          "name": { "display_strings": { "en": "Page 1", "es": "Página 1", "fr": "Page 1" } },
          "param_oids": ["/counter", "/hello"]
        },
        "page_2": {
          "name": { "display_strings": { "en": "Page 2", "es": "Página 2", "fr": "Page 2" }},
          "param_oids": ["/offset", "/button", "/inline_button", "/counter"]
        }
      },
      "order": 1
    }
  },
  "params": {
    "product": {
      "type": "STRUCT",
      "access_scope": "st2138:mon",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "Use Menus" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING"
        },
        "vendor": {
          "type": "STRING"
        },
        "version": {
          "type": "STRING"
        },
        "catena_sdk": {
          "type": "STRING"
        },
        "catena_sdk_version": {
          "type": "STRING"
        },
        "serial_number": {
          "type": "STRING"
        }
      }
    },
    "counter": {
      "type": "INT32",
      "name": { "display_strings": { "en": "Counter", "es": "Contador", "fr": "Compteur" } },
      "value": { "int32_value": 0 }
    },
    "hello": {
      "type": "STRING",
      "name": { "display_strings": { "en": "Text Box", "es": "Caja de texto", "fr": "Boîte de texte" } },
      "access_scope": "st2138:cfg",
      "value": { "string_value": "Hello, World!" }
    },
    "button": {
      "type": "INT32",
      "name": { "display_strings": { "en": "Button", "es": "Botón", "fr": "Bouton" } },
      "value": { "int32_value": 0 },
      "widget": "toggle",
      "constraint": { "ref_oid": "basic_button" }
    },
    "inline_button": {
      "type": "INT32",
      "name": { "display_strings": { "en": "Inline Button", "es": "Botón en línea", "fr": "Bouton en ligne" } },
      "value": { "int32_value": 0 },
      "widget": "toggle",
      "constraint": {
        "type": "INT_CHOICE",
        "int32_choice": {
          "choices": [
            {  "name": { "display_strings": { "en": "Off", "es": "Apagado", "fr": "Éteint" } },  "value": 0 },
            {  "name": { "display_strings": { "en": "On", "es": "Encendido", "fr": "Allumé" } }, "value": 1 }
          ]
        }
      }
    },
    "offset": {
      "type": "INT32",
      "name": { "display_strings": { "en": "offset" } },
      "access_scope": "st2138:cfg",
      "value": { "int32_value": 0 },
      "constraint": {
        "type": "INT_RANGE",
        "int32_range": {
          "min_value": -10,
          "max_value": 10,
          "step": 1
        }
      }
    }
  },
  "constraints": {
    "basic_button": {
      "type": "INT_CHOICE",
      "int32_choice": {
        "choices": [
          { "name": { "display_strings": { "en": "Off", "es": "Apagado", "fr": "Éteint" } },  "value": 0  },
          { "name": { "display_strings": { "en": "On", "es": "Encendido", "fr": "Allumé" } }, "value": 1 }
        ]
      }
    }
  }
}

=== rossvideo/Catena/example_device_models/device.one_of_everything.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["monitor", "operate", "configure", "administer"],
  "default_scope": "operate",
  "params": {
    "a_number": {
      "type": "INT32",
      "value": { "int32_value": 1234 },
      "name": { "display_strings": { "en": "Int Example" } }
    },
    "float_example": {
      "type": "FLOAT32",
      "value": { "float32_value": 1234.5678},
      "name": { "display_strings": { "en": "Float Example" } }
    },
    "string_example": {
      "type": "STRING",
      "value": { "string_value": "Hello, World!" },
      "name": { "display_strings": { "en": "String Example" } }
    },
    "number_array": {
      "type": "INT32_ARRAY",
      "value": { "int32_array_values": { "ints": [1, 2, 3, 4] } },
      "name": { "display_strings": { "en": "Int Array Example" } }
    },
    "location": {
      "type": "STRUCT",
      "params": {
        "latitude": {
          "type": "FLOAT32",
          "name": {
            "display_strings": {
              "en": "Latitude"
            }
          },
          "value": {
            "float32_value": 37.7749
          }
        },
        "longitude": {
          "type": "FLOAT32",
          "name": {
            "display_strings": {
              "en": "Longitude"
            }
          },
          "value": {
            "float32_value": -122.4194
          }
        }
      },
      "name": {
        "display_strings": {
          "en": "Location"
        }
      },
      "value": {
        "struct_value": {
          "fields": {
            "latitude": {
              "value": {
                "float32_value": 37.7749
              }
            },
            "longitude": {
              "value": {
                "float32_value": -122.4194
              }
            }
          }
        }
      }
    }
  },
  "menu_groups": {
    "status_group": {
      "name": { "display_strings": { "en": "Status" } },
      "menus": {
        "status": {
          "name": { "display_strings": { "en": "Product" } },
          "param_oids": ["/a_number"]
        }
      }
    },
    "config_group": {
      "name": { "display_strings": { "en": "Config" } },
      "menus": {
        "config": {
          "name": { "display_strings": { "en": "Catena" } },
          "param_oids": ["/string_example", "/float_example"]
        }
      }
    }
  }
}
