=== rossvideo/Catena/schema/catena.device_schema.json
{
  "$id": "catena.device_schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Catena Device Model Schema",
  "description": "Intended to assist humans to author Catena device models as JSON files as some IDEs can use schemata such as this one to lint models.",
  "type": "object",
  "properties": {
    "slot": {
      "$ref": "#/$defs/slot"
    },
    "detail_level": {
      "$ref": "#/$defs/detail_level"
    },
    "multi_set_enabled": {
      "title": "Multi Set Message Enabled Flag",
      "description": "Enables use of the multi-value message to report multiple parameter changes in one message. Otherwise changes will be reported individually using the value message. Defaults to true.",
      "type": "boolean"
    },
    "subscriptions": {
      "title": "Subscriptions Flag",
      "description": "When true, indicates that the device supports subscription-based access to subsets of parameters.",
      "type": "boolean"
    },
    "constraints": {
      "$ref": "#/$defs/constraint_map"
    },
    "params": {
      "type": "object",
      "patternProperties": {
        "^((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)(\\/((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)){0,31}$": {
          "$ref": "catena.param_schema.json#"
        }
      }
    },
    "commands": {
      "type": "object",
      "patternProperties": {
        "^((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)(\\/((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)){0,31}$": {
          "$ref": "catena.param_schema.json#"
        }
      }
    },
    "access_scopes": {
      "title": "Access Scopes",
      "description": "The access scopes recognised by this device",
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true,
        "maxItems": 5,
        "$comment": "discussion needed on min & max items"
      },
      "additionalItems": false
    },
    "default_scope": {
      "$id": "Default Access Scope",
      "description": "Objects in the model will have this access scope unless overridden explicitly, or implicitly by inheritance",
      "type": "string"
    },
    "language_packs": {
      "$ref": "#/$defs/language_packs",
      "additionalProperties": true,
      "description": "The devices language packs"
    },
    "menu_groups": { "$ref": "#/$defs/menu_groups" }
  },
  "required": ["slot"],
  "additionalProperties": false,
  "$defs": {
    "external_object_payload": {
      "title": "External Object Payload",
      "description": "A payload for an external object",
      "type": "object",
      "properties": {
        "data": { "type": "string" }
      }
    },
    "menu_groups": {
      "title": "Menu Groups",
      "description": "An operationally logical grouping of menus.",
      "type": "object",
      "patternProperties": {
        "^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$": {
          "$ref": "#/$defs/menu_group"
        }
      },
      "additionalProperties": false
    },
    "menu_group": {
      "title": "Menu Group",
      "description": "A group of menus",
      "type": "object",
      "properties": {
        "name": { "$ref": "catena.param_schema.json#/$defs/polyglot_text" },
        "menus": { "$ref": "#/$defs/menus" }
      },
      "additionalProperties": false
    },
    "menus": {
      "title": "Menus",
      "description": "The menus recognised by this device",
      "type": "object",
      "patternProperties": {
        "^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$": {
          "$ref": "#/$defs/menu"
        }
      },
      "additionalProperties": false
    },
    "menu": {
      "title": "Menu",
      "description": "A menu",
      "type": "object",
      "properties": {
        "name": { "$ref": "catena.param_schema.json#/$defs/polyglot_text" },
        "param_oids": { "$ref": "#/$defs/oids_list" },
        "command_oids": { "$ref": "#/$defs/oids_list" },
        "client_hints": { "$ref": "catena.param_schema.json#/$defs/client_hints" },
        "hidden": {
          "type": "boolean",
          "default": false
        },
        "disabled": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "oids_list": {
      "title": "OIDs List",
      "description": "A list of Fully Qualified Object IDs",
      "type": "array",
      "items": { "type": "string", "format": "json-pointer" },
      "additionalItems": false
    },
    "language_pack": {
      "properties": {
        "name": {
          "type": "string"
        },
        "words": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "additionalProperties": true,
      "type": "object",
      "title": "Language Pack",
      "description": "Language Pack A map of string identifiers, e.g. \"greeting\" to strings which are all in the same language."
    },
    "language_packs": {
      "properties": {
        "packs": {
          "additionalProperties": {
            "$ref": "#/$defs/language_pack",
            "additionalProperties": true
          },
          "type": "object"
        }
      },
      "additionalProperties": true,
      "type": "object",
      "title": "Language Packs",
      "description": "Language Packs A map of language identifiers to resource dictionaries or language packs for each language supported. The keys shall be patterned on those defined in https://www.mesaonline.org/language-metadata-table, e.g. \"es\" for Global Spanish. \"es-CO\" for Colombian Spanish. \"pl\" for Jezyk polski"
    },
    "constraint_map": {
      "title": "map of constraints used for top-level shared constraints",
      "description": "Defines the collection of constraints that are able to be shared amongst params or commands within a device.",
      "type": "object",
      "$comment": "patternProperties regex must be same as that defined in oid schema",
      "patternProperties": {
        "(^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$)": {
          "$ref": "catena.param_schema.json#/$defs/constraint"
        }
      },
      "additionalProperties": false
    },
    "slot": {
      "title": "Slot ID",
      "description": "Uniquely identifies the device within the scope of its Catena connection",
      "type": "integer",
      "minimum": 0,
      "maximum": 65535,
      "default": 0
    },
    "slot_list": {
      "title": "Slot List",
      "description": "A list of slot IDs",
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "items": {
        "$ref": "#/$defs/slot"
      },
      "additionalItems": false
    },
    "detail_level": {
      "title": "Level of Detail",
      "description": "The level of detail in device messages and parameter updates. 'full' indicates that all parameters are reported, 'minimal' that only the minimal set is, 'subscription' reports the minimal set plus identified subscribed parameters, 'commands' reports only descriptors for commands and not for parameters, and 'none' indicates that no parameters or commands should be automatically reported by the device (parameter descriptors, command descriptors, and values can still be pulled). ",
      "type": "string",
      "enum": ["FULL", "SUBSCRIPTIONS", "MINIMAL", "COMMANDS", "NONE"],
      "default": "FULL"
    }
  }
}

=== rossvideo/Catena/sdks/cpp/lite/examples/use_struct_arrays/device.AudioDeck.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["monitor", "operate", "configure", "administer"],
  "default_scope": "operate",
  "language_packs": {},
  "params": {
    "eq": {
      "type": "STRUCT",
      "name": { "display_strings": { "en": "EQ" } },
      "params": {
        "response": {
          "type": "INT32",
          "name": { "display_strings": { "en": "Response" } }
        },
        "frequency": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Frequency" } }
        },
        "gain": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Gain" } }
        },
        "q_factor": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Q Factor" } }
        }
      }
    },
    "audio_channel": {
      "type": "STRUCT",
      "name": { "display_strings": { "en": "Audio Channel" } },
      "params": {
        "fader": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Fader" } }
        },
        "eq_list": {
          "type": "STRUCT_ARRAY",
          "name": { "display_strings": { "en": "EQ List" } },
          "template_oid": "/eq",
          "value": {
            "struct_array_values": {
              "struct_values": [
                {
                  "struct_value": {
                    "fields": {
                      "response": { "value": {"int32_value": 0}},
                      "frequency": { "value": {"float32_value": 0}},
                      "gain": { "value": {"float32_value": 0}},
                      "q_factor": { "value": {"float32_value": 0}}
                    }
                  }
                },
                {
                  "struct_value": {
                    "fields": {
                      "response": { "value": {"int32_value": 0}},
                      "frequency": { "value": {"float32_value": 0}},
                      "gain": { "value": {"float32_value": 0}},
                      "q_factor": { "value": {"float32_value": 0}}
                    }
                  }
                }
              ]
            }
          }
        }
      }
    },
    "audio_deck": {
      "type": "STRUCT_ARRAY",
      "name": { "display_strings": { "en": "Audio Deck" } },
      "template_oid": "/audio_channel",
      "value": {
        "struct_array_values": {
          "struct_values": [
            {
              "struct_value": {
                "fields": {
                  "fader":{"value": {"float32_value": 0.5}},
                  "eq_list": {
                    "value": {
                      "struct_array_values": {
                        "struct_values": [
                          {
                            "struct_value": {
                              "fields": {
                                "response": { "value": {"int32_value": 1}},
                                "frequency": { "value": {"float32_value": 100}},
                                "gain": { "value": {"float32_value": 0}},
                                "q_factor": { "value": {"float32_value": 0}}
                              }
                            }
                          },
                          {
                            "struct_value": {
                              "fields": {
                                "response": { "value": {"int32_value": 2}},
                                "frequency": { "value": {"float32_value": 200}},
                                "gain": { "value": {"float32_value": 0}},
                                "q_factor": { "value": {"float32_value": 0}}
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            },
            {
              "struct_value": {
                "fields": {
                  "fader":{"value": {"float32_value": 0.5}},
                  "eq_list": {
                    "value": {
                      "struct_array_values": {
                        "struct_values": [
                          {
                            "struct_value": {
                              "fields": {
                                "response": { "value": {"int32_value": 1}},
                                "frequency": { "value": {"float32_value": 100}},
                                "gain": { "value": {"float32_value": 0}},
                                "q_factor": { "value": {"float32_value": 0}}
                              }
                            }
                          },
                          {
                            "struct_value": {
                              "fields": {
                                "response": { "value": {"int32_value": 2}},
                                "frequency": { "value": {"float32_value": 200}},
                                "gain": { "value": {"float32_value": 0}},
                                "q_factor": { "value": {"float32_value": 0}}
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            },
            {
              "struct_value": {
                "fields": {
                  "fader":{"value": {"float32_value": 0.5}},
                  "eq_list": {
                    "value": {
                      "struct_array_values": {
                        "struct_values": [
                          {
                            "struct_value": {
                              "fields": {
                                "response": { "value": {"int32_value": 1}},
                                "frequency": { "value": {"float32_value": 100}},
                                "gain": { "value": {"float32_value": 0}},
                                "q_factor": { "value": {"float32_value": 0}}
                              }
                            }
                          },
                          {
                            "struct_value": {
                              "fields": {
                                "response": { "value": {"int32_value": 2}},
                                "frequency": { "value": {"float32_value": 200}},
                                "gain": { "value": {"float32_value": 0}},
                                "q_factor": { "value": {"float32_value": 0}}
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            },
            {
              "struct_value": {
                "fields": {
                  "fader":{"value": {"float32_value": 0.5}},
                  "eq_list": {
                    "value": {
                      "struct_array_values": {
                        "struct_values": [
                          {
                            "struct_value": {
                              "fields": {
                                "response": { "value": {"int32_value": 1}},
                                "frequency": { "value": {"float32_value": 100}},
                                "gain": { "value": {"float32_value": 0}},
                                "q_factor": { "value": {"float32_value": 0}}
                              }
                            }
                          },
                          {
                            "struct_value": {
                              "fields": {
                                "response": { "value": {"int32_value": 2}},
                                "frequency": { "value": {"float32_value": 200}},
                                "gain": { "value": {"float32_value": 0}},
                                "q_factor": { "value": {"float32_value": 0}}
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/REST/examples/discovery_REST/device.discovery.json
{
  "slot": 0,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "subscriptions": true,
  "params": {
    "assets": {
      "type": "STRING_ARRAY",
      "name": { "display_strings": { "en": "Assets", "es": "Assets", "fr": "Assets" } },
      "value": { "string_array_values": { "strings": [] } }
    },
    "product": {
      "type": "STRUCT",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "Video Player" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "vendor": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "version": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "catena_sdk": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "catena_sdk_version": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "serial_number": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        }
      }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/common/examples/use_variants/device.use_variants.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": [
    "st2138:mon",
    "st2138:op",
    "st2138:cfg",
    "st2138:adm"
  ],
  "default_scope": "st2138:op",
  "params": {
    "product": {
      "type": "STRUCT",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "External Object Request" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING"
        },
        "vendor": {
          "type": "STRING"
        },
        "version": {
          "type": "STRING"
        },
        "catena_sdk": {
          "type": "STRING"
        },
        "catena_sdk_version": {
          "type": "STRING"
        },
        "serial_number": {
          "type": "STRING"
        }
      }
    },
    "number": {
      "type": "STRUCT_VARIANT",
      "params" : {
        "words": {
          "type": "STRING"
        },
        "digits": {
          "type": "INT32"  
        }
      },
      "value": {
        "struct_variant_value": {
          "struct_variant_type": "words",
          "value": {
            "string_value": "one"
          }
        }
      }
    },
    "cartesian": {
      "type": "STRUCT",
      "params": {
        "x": {
          "type": "INT32"
        },
        "y": {
          "type": "INT32"
        },
        "z": {
          "type": "INT32"
        }
      },
      "value": {
        "struct_value": {
          "fields": {
            "x": {"int32_value": 5},
            "y": {"int32_value": 10},
            "z": {"int32_value": 15}
          }
        }
      }
    },
    "coordinates": {
      "type": "STRUCT_VARIANT_ARRAY",
      "params": {
        "cartesian": {
          "type": "STRUCT",
          "template_oid": "/cartesian"
        },
        "cylindrical": {
          "type": "STRUCT",
          "params": {
            "rho": {
              "type": "INT32"
            },
            "phi": {
              "type": "INT32",
              "constraint": {
                "type": "INT_RANGE",
                "int32_range": {
                  "min_value": 0,
                  "max_value": 360
                }
              }
            },
            "z": {
              "type": "INT32"
            }
          }
        },
        "spherical": {
          "type": "STRUCT",
          "params": {
            "r": {
              "type": "INT32"
            },
            "phi": {
              "type": "INT32",
              "constraint": {
                "type": "INT_RANGE",
                "int32_range": {
                  "min_value": 0,
                  "max_value": 180
                }
              }
            },
            "theta": {
              "type": "INT32",
              "constraint": {
                "type": "INT_RANGE",
                "int32_range": {
                  "min_value": 0,
                  "max_value": 360
                }
              }
            }
          }
        }
      },
      "value": {
        "struct_variant_array_values": {
          "struct_variants": [
            {
              "struct_variant_value": {
                "struct_variant_type": "cartesian",
                "value": {
                  "struct_value": {
                    "fields": {
                      "x": {"int32_value": 1},
                      "y": {"int32_value": 2},
                      "z": {"int32_value": 3}
                    }
                  }
                }
              }
            },
            {
              "struct_variant_value": {
                "struct_variant_type": "cylindrical",
                "value": {
                  "struct_value": {
                    "fields": {
                      "rho": {"int32_value": 1},
                      "phi": {"int32_value": 90},
                      "z": {"int32_value": 3}
                    }
                  }
                }
              }
            },
            {
              "struct_variant_value": {
                "struct_variant_type": "spherical",
                "value": {
                  "struct_value": {
                    "fields": {
                      "r": {"int32_value": 1},
                      "theta": {"int32_value": 90},
                      "phi": {"int32_value": 180}
                    }
                  }
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/gRPC/examples/multi_device/device.a.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st-2138:mon", "st-2138:op", "st-2138:cfg", "st-2138:adm"],
  "default_scope": "st-2138:op",
  "subscriptions": true,
  "language_packs": {
    "packs": {
      "es": {
        "name": "Spanish",
        "words": {
          "greeting": "Hola",
          "parting": "Adiós"
        }
      },
      "en": {
        "name": "English",
        "words": {
          "greeting": "Hello",
          "parting": "Goodbye"
        }
      },
      "fr": {
        "name": "French",
        "words": {
          "greeting": "Bonjour",
          "parting": "Adieu"
        }
      }
    }
  },
  "params": {
    "text_box": {
      "type": "STRING",
      "name": { "display_strings": { "en": "Text Box", "es": "Caja de Texto", "fr": "Boîte de Texte" } },
      "access_scope": "st-2138:cfg",
      "value": { "string_value": "This is device a" }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/common/examples/hello_world/device.hello_world.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "language_packs": {
    "packs": {
      "es": {
        "name": "Spanish",
        "words": {
          "greeting": "Hola",
          "parting": "Adiós"
        }
      },
      "en": {
        "name": "English",
        "words": {
          "greeting": "Hello",
          "parting": "Goodbye"
        }
      },
      "fr": {
        "name": "French",
        "words": {
          "greeting": "Bonjour",
          "parting": "Adieu"
        }
      }
    }
  },
  "params": {
    "product": {
      "type": "STRUCT",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "Hello World" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING"
        },
        "vendor": {
          "type": "STRING"
        },
        "version": {
          "type": "STRING"
        },
        "catena_sdk": {
          "type": "STRING"
        },
        "catena_sdk_version": {
          "type": "STRING"
        },
        "serial_number": {
          "type": "STRING"
        }
      }
    },
    "hello": {
      "type": "STRING",
      "name": { "display_strings": { "$key": "greeting" } },
      "value": { "string_value": "Hello, World!" }
    },
    "count": {
      "type": "INT32",
      "value": { "int32_value": 1234 },
      "name": { "display_strings": { "en": "Counter" } }
    },
    "gain": {
      "type": "FLOAT32",
      "value": { "float32_value": 0.707 },
      "name": { "display_strings": { "en": "Audio Gain" } },
      "widget": "fader"
    },
    "phonetic_alphabet": {
      "type": "STRING_ARRAY",
      "name": { "display_strings": { "en": "Phonetic Alphabet" } },
      "value": {
        "string_array_values": {
          "strings": ["Alpha", "Bravo", "Charlie", "..."]
        }
      }
    },
    "primes": {
      "type": "INT32_ARRAY",
      "name": { "display_strings": { "en": "The First Few Primes" } },
      "value": {
        "int32_array_values": {
          "ints": [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
        }
      }
    },
    "physical_constants": {
      "type": "FLOAT32_ARRAY",
      "name": { "display_strings": { "en": "Some Physical Constants" } },
      "value": {
        "float32_array_values": {
          "floats": []
        }
      }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/common/examples/use_templates/device.use_templates.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon","st2138:op","st2138:cfg","st2138:adm"],
  "default_scope": "st2138:op",
  "language_packs": {},
  "params": {
    "product": {
      "type": "STRUCT",
      "access_scope": "st2138:mon",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "External Object Request" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING"
        },
        "vendor": {
          "type": "STRING"
        },
        "version": {
          "type": "STRING"
        },
        "catena_sdk": {
          "type": "STRING"
        },
        "catena_sdk_version": {
          "type": "STRING"
        },
        "serial_number": {
          "type": "STRING"
        }
      }
    },
    "city": {
      "type": "STRUCT",
      "name": {
        "display_strings": {
          "en": "City"
        }
      },
      "params": {
        "city_name": {
          "type": "STRING",
          "name": {
            "display_strings": {
              "en": "Name"
            }
          }
        },
        "latitude": {
          "type": "FLOAT32",
          "name": {
            "display_strings": {
              "en": "Latitude"
            }
          }
        },
        "longitude": {
          "type": "FLOAT32",
          "name": {
            "display_strings": {
              "en": "Longitude"
            }
          }
        },
        "population": {
          "type": "INT32",
          "name": {
            "display_strings": {
              "en": "Population"
            }
          }
        }
      }
    },
    "ottawa": {
      "type": "STRUCT",
      "template_oid": "/city",
      "name": {
        "display_strings": {
          "en": "Ottawa"
        }
      },
      "value": {
        "struct_value": {
          "fields": {
            "city_name": {"string_value": "Ottawa"},
            "latitude": {"float32_value": 45.4215},
            "longitude": {"float32_value": -75.6972},
            "population": {"int32_value": 934243}
          }
        }
      }
    },
    "toronto": {
      "type": "STRUCT",
      "template_oid": "/city",
      "name": {
        "display_strings": {
          "en": "Toronto"
        }
      },
      "value": {
        "struct_value": {
          "fields": {
            "city_name": {"string_value": "Toronto"},
            "latitude": {"float32_value": 43.6511},
            "longitude": {"float32_value": -79.3470},
            "population": {"int32_value": 2731571}
          }
        }
      }
    }
  }
}
