=== rossvideo/Catena/schema/catena.device_schema.json
{
  "$id": "catena.device_schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Catena Device Model Schema",
  "description": "Intended to assist humans to author Catena device models as JSON files as some IDEs can use schemata such as this one to lint models.",
  "type": "object",
  "properties": {
    "slot": {
      "$ref": "#/$defs/slot"
    },
    "detail_level": {
      "$ref": "#/$defs/detail_level"
    },
    "multi_set_enabled": {
      "title": "Multi Set Message Enabled Flag",
      "description": "Enables use of the multi-value message to report multiple parameter changes in one message. Otherwise changes will be reported individually using the value message. Defaults to true.",
      "type": "boolean"
    },
    "subscriptions": {
      "title": "Subscriptions Flag",
      "description": "When true, indicates that the device supports subscription-based access to subsets of parameters.",
      "type": "boolean"
    },
    "constraints": {
      "$ref": "#/$defs/constraint_map"
    },
    "params": {
      "type": "object",
      "patternProperties": {
        "^((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)(\\/((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)){0,31}$": {
          "$ref": "catena.param_schema.json#"
        }
      }
    },
    "commands": {
      "type": "object",
      "patternProperties": {
        "^((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)(\\/((?![\\w.]*\\.\\d+$)[a-zA-Z][\\w.]{0,62}|\\d+|-)){0,31}$": {
          "$ref": "catena.param_schema.json#"
        }
      }
    },
    "access_scopes": {
      "title": "Access Scopes",
      "description": "The access scopes recognised by this device",
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true,
        "maxItems": 5,
        "$comment": "discussion needed on min & max items"
      },
      "additionalItems": false
    },
    "default_scope": {
      "$id": "Default Access Scope",
      "description": "Objects in the model will have this access scope unless overridden explicitly, or implicitly by inheritance",
      "type": "string"
    },
    "language_packs": {
      "$ref": "#/$defs/language_packs",
      "additionalProperties": true,
      "description": "The devices language packs"
    },
    "menu_groups": { "$ref": "#/$defs/menu_groups" }
  },
  "required": ["slot"],
  "additionalProperties": false,
  "$defs": {
    "external_object_payload": {
      "title": "External Object Payload",
      "description": "A payload for an external object",
      "type": "object",
      "properties": {
        "data": { "type": "string" }
      }
    },
    "menu_groups": {
      "title": "Menu Groups",
      "description": "An operationally logical grouping of menus.",
      "type": "object",
      "patternProperties": {
        "^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$": {
          "$ref": "#/$defs/menu_group"
        }
      },
      "additionalProperties": false
    },
    "menu_group": {
      "title": "Menu Group",
      "description": "A group of menus",
      "type": "object",
      "properties": {
        "name": { "$ref": "catena.param_schema.json#/$defs/polyglot_text" },
        "menus": { "$ref": "#/$defs/menus" }
      },
      "additionalProperties": false
    },
    "menus": {
      "title": "Menus",
      "description": "The menus recognised by this device",
      "type": "object",
      "patternProperties": {
        "^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$": {
          "$ref": "#/$defs/menu"
        }
      },
      "additionalProperties": false
    },
    "menu": {
      "title": "Menu",
      "description": "A menu",
      "type": "object",
      "properties": {
        "name": { "$ref": "catena.param_schema.json#/$defs/polyglot_text" },
        "param_oids": { "$ref": "#/$defs/oids_list" },
        "command_oids": { "$ref": "#/$defs/oids_list" },
        "client_hints": { "$ref": "catena.param_schema.json#/$defs/client_hints" },
        "hidden": {
          "type": "boolean",
          "default": false
        },
        "disabled": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "oids_list": {
      "title": "OIDs List",
      "description": "A list of Fully Qualified Object IDs",
      "type": "array",
      "items": { "type": "string", "format": "json-pointer" },
      "additionalItems": false
    },
    "language_pack": {
      "properties": {
        "name": {
          "type": "string"
        },
        "words": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "additionalProperties": true,
      "type": "object",
      "title": "Language Pack",
      "description": "Language Pack A map of string identifiers, e.g. \"greeting\" to strings which are all in the same language."
    },
    "language_packs": {
      "properties": {
        "packs": {
          "additionalProperties": {
            "$ref": "#/$defs/language_pack",
            "additionalProperties": true
          },
          "type": "object"
        }
      },
      "additionalProperties": true,
      "type": "object",
      "title": "Language Packs",
      "description": "Language Packs A map of language identifiers to resource dictionaries or language packs for each language supported. The keys shall be patterned on those defined in https://www.mesaonline.org/language-metadata-table, e.g. \"es\" for Global Spanish. \"es-CO\" for Colombian Spanish. \"pl\" for Jezyk polski"
    },
    "constraint_map": {
      "title": "map of constraints used for top-level shared constraints",
      "description": "Defines the collection of constraints that are able to be shared amongst params or commands within a device.",
      "type": "object",
      "$comment": "patternProperties regex must be same as that defined in oid schema",
      "patternProperties": {
        "(^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$)": {
          "$ref": "catena.param_schema.json#/$defs/constraint"
        }
      },
      "additionalProperties": false
    },
    "slot": {
      "title": "Slot ID",
      "description": "Uniquely identifies the device within the scope of its Catena connection",
      "type": "integer",
      "minimum": 0,
      "maximum": 65535,
      "default": 0
    },
    "slot_list": {
      "title": "Slot List",
      "description": "A list of slot IDs",
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "items": {
        "$ref": "#/$defs/slot"
      },
      "additionalItems": false
    },
    "detail_level": {
      "title": "Level of Detail",
      "description": "The level of detail in device messages and parameter updates. 'full' indicates that all parameters are reported, 'minimal' that only the minimal set is, 'subscription' reports the minimal set plus identified subscribed parameters, 'commands' reports only descriptors for commands and not for parameters, and 'none' indicates that no parameters or commands should be automatically reported by the device (parameter descriptors, command descriptors, and values can still be pulled). ",
      "type": "string",
      "enum": ["FULL", "SUBSCRIPTIONS", "MINIMAL", "COMMANDS", "NONE"],
      "default": "FULL"
    }
  }
}

=== rossvideo/Catena/nab_2024/device.analyzer.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["monitor", "operate", "configure", "administer"],
  "default_scope": "operate",
  "params": {
    "analysis": {
      "type": "INT32",
      "value": { "int32_value": 0 },
      "name": { "display_strings": { "en": "Analyzer Mode" } },
      "constraint": {
        "type": "INT_CHOICE",
        "int32_choice": {
          "choices": [
            { "value": 0, "name": { "display_strings": { "en": "Show st20 RAISR" } } },
            { "value": 1, "name": { "display_strings": { "en": "Show st22 JPEGxs" } } },
            { "value": 2, "name": { "display_strings": { "en": "Diff st20/st22" } } },
            { "value": 3, "name": { "display_strings": { "en": "Diff st22/st20" } } },
            { "value": 4, "name": { "display_strings": { "en": "W.Div st20/st22" } } },
            { "value": 5, "name": { "display_strings": { "en": "W.Div st22/st20" } } },
            { "value": 6, "name": { "display_strings": { "en": "Cmpr st20/st22" } } },
            { "value": 7, "name": { "display_strings": { "en": "Cmpr st22/st20" } } }
          ]
        }
      },
      "widget": "radio",
      "access_scope": "operate"
    },
    "amplification": {
      "type": "FLOAT32",
      "value": { "float32_value": 1.0 },
      "name": { "display_strings": { "en": "Difference amplification" } },
      "widget": "default",
      "access_scope": "operate",
      "constraint": {
        "type": "FLOAT_RANGE",
        "float_range": {
          "min_value": 0.0,
          "max_value": 1000.0,
          "step": 0.1
        }
      },
      "precision": 2
    },
    "product": {
        "type": "STRING",
        "value": { "string_value": "Catena + MCM Demo" },
        "name": { "display_strings": { "en": "Product" } },
        "read_only": true,
        "access_scope": "monitor"
    },
    "partners": {
        "type": "STRING_ARRAY",
        "value": {
            "string_array_values": {
                "strings": ["Ross Video", "Intel", "Cisco"]
            }
        },
        "name": { "display_strings": { "en": "Partners" } },
        "read_only": true,
        "access_scope": "monitor"
    },
    "a_number": {
      "type": "INT32",
      "name": {
        "display_strings": {
          "en": "A Number"
        }
      },
      "value": {
        "int32_value": 42
      },
      "stateless": true
    }
  },
  "menu_groups": {
    "status": {
      "name": { "display_strings": { "en": "Status" } },
      "menus": {
        "status": {
          "name": { "display_strings": { "en": "Product" } },
          "param_oids": ["/product", "/partners"]
        }
      }
    },
    "config": {
      "name": { "display_strings": { "en": "Config" } },
      "menus": {
        "config": {
          "name": { "display_strings": { "en": "Analyzer" } },
          "param_oids": ["/analysis","/amplification"]
        }
      }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/common/examples/use_struct_arrays/device.AudioDeck.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "language_packs": {},
  "params": {
    "product": {
      "type": "STRUCT",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "External Object Request" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "vendor": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "version": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "catena_sdk": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "catena_sdk_version": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "serial_number": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        }
      }
    },
    "eq": {
      "type": "STRUCT",
      "name": { "display_strings": { "en": "EQ" } },
      "params": {
        "response": {
          "type": "INT32",
          "name": { "display_strings": { "en": "Response" } }
        },
        "frequency": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Frequency" } }
        },
        "gain": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Gain" } }
        },
        "q_factor": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Q Factor" } }
        }
      }
    },
    "audio_channel": {
      "type": "STRUCT",
      "name": { "display_strings": { "en": "Audio Channel" } },
      "params": {
        "fader": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Fader" } }
        },
        "eq_list": {
          "type": "STRUCT_ARRAY",
          "name": { "display_strings": { "en": "EQ List" } },
          "template_oid": "/eq",
          "value": {
            "struct_array_values": {
              "struct_values": [
                {
                  "struct_value": {
                    "fields": {
                      "response": {"int32_value": 0},
                      "frequency": {"float32_value": 0},
                      "gain": {"float32_value": 0},
                      "q_factor": {"float32_value": 0}
                    }
                  }
                },
                {
                  "struct_value": {
                    "fields": {
                      "response": {"int32_value": 0},
                      "frequency": {"float32_value": 0},
                      "gain": {"float32_value": 0},
                      "q_factor": {"float32_value": 0}
                    }
                  }
                }
              ]
            }
          }
        }
      }
    },
    "audio_deck": {
      "type": "STRUCT_ARRAY",
      "name": { "display_strings": { "en": "Audio Deck" } },
      "template_oid": "/audio_channel",
      "value": {
        "struct_array_values": {
          "struct_values": [
            {
              "struct_value": {
                "fields": {
                  "fader": {"float32_value": 0.0},
                  "eq_list": {
                    "struct_array_values": {
                      "struct_values": [
                        {
                          "struct_value": {
                            "fields": {
                              "response": {"int32_value": 1},
                              "frequency": {"float32_value": 100},
                              "gain": {"float32_value": 0},
                              "q_factor": {"float32_value": 0}
                            }
                          }
                        },
                        {
                          "struct_value": {
                            "fields": {
                              "response": {"int32_value": 2},
                              "frequency": {"float32_value": 200},
                              "gain": {"float32_value": 0},
                              "q_factor": {"float32_value": 0}
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            },
            {
              "struct_value": {
                "fields": {
                  "fader":{"float32_value": 0.1},
                  "eq_list": {
                    "struct_array_values": {
                      "struct_values": [
                        {
                          "struct_value": {
                            "fields": {
                              "response": {"int32_value": 3},
                              "frequency": {"float32_value": 300},
                              "gain": {"float32_value": 0},
                              "q_factor": {"float32_value": 0}
                            }
                          }
                        },
                        {
                          "struct_value": {
                            "fields": {
                              "response": {"int32_value": 4},
                              "frequency": {"float32_value": 400},
                              "gain": {"float32_value": 0},
                              "q_factor": {"float32_value": 0}
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            },
            {
              "struct_value": {
                "fields": {
                  "fader":{"float32_value": 0.2},
                  "eq_list": {
                    "struct_array_values": {
                      "struct_values": [
                        {
                          "struct_value": {
                            "fields": {
                              "response": {"int32_value": 5},
                              "frequency": {"float32_value": 500},
                              "gain": {"float32_value": 0},
                              "q_factor": {"float32_value": 0}
                            }
                          }
                        },
                        {
                          "struct_value": {
                            "fields": {
                              "response": {"int32_value": 6},
                              "frequency": {"float32_value": 600},
                              "gain": {"float32_value": 0},
                              "q_factor": {"float32_value": 0}
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            },
            {
              "struct_value": {
                "fields": {
                  "fader":{"float32_value": 0.3},
                  "eq_list": {
                    "struct_array_values": {
                      "struct_values": [
                        {
                          "struct_value": {
                            "fields": {
                              "response": {"int32_value": 7},
                              "frequency": {"float32_value": 700},
                              "gain": {"float32_value": 0},
                              "q_factor": {"float32_value": 0}
                            }
                          }
                        },
                        {
                          "struct_value": {
                            "fields": {
                              "response": {"int32_value": 8},
                              "frequency": {"float32_value": 800},
                              "gain": {"float32_value": 0},
                              "q_factor": {"float32_value": 0}
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/gRPC/examples/external_object_request/device.external_object_request.json
{
  "slot": 0,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "language_packs": {
    "packs": {
      "es": {
        "name": "Spanish",
        "words": {
          "greeting": "Hola",
          "parting": "Adiós"
        }
      },
      "en": {
        "name": "English",
        "words": {
          "greeting": "Hello",
          "parting": "Goodbye"
        }
      },
      "fr": {
        "name": "French",
        "words": {
          "greeting": "Bonjour",
          "parting": "Adieu"
        }
      }
    }
  },
  "params": {
    "product": {
      "type": "STRUCT",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "Status Update" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING"
        },
        "vendor": {
          "type": "STRING"
        },
        "version": {
          "type": "STRING"
        },
        "catena_sdk": {
          "type": "STRING"
        },
        "catena_sdk_version": {
          "type": "STRING"
        },
        "serial_number": {
          "type": "STRING"
        }
      }
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/gRPC/examples/multi_device/device.video_player_a.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "subscriptions": false,

  "language_packs": {
    "packs": {
      "es": {
        "name": "Spanish",
        "words": {
          "greeting": "Hola",
          "parting": "Adiós"
        }
      },
      "en": {
        "name": "English",
        "words": {
          "greeting": "Hello",
          "parting": "Goodbye"
        }
      },
      "fr": {
        "name": "French",
        "words": {
          "greeting": "Bonjour",
          "parting": "Adieu"
        }
      }
    }
  },

  "params": {
    "state": {
      "type": "STRING",
      "name": { "display_strings": { "en": "State a" } },
      "read_only": true,
      "value": { "string_value": "stopped" },
      "constraint": {
        "type": "STRING_CHOICE",
        "string_choice": {
          "choices": ["stopped", "playing", "paused", "rewinding", "fast_forwarding"],
          "strict": true
        }
      }
    },
    "video_file": {
      "type": "STRING",
      "name": { "display_strings": { "en": "Video file a" } },
      "value": { "string_value": "eo://video/1" },
      "constraint": {
        "type": "STRING_CHOICE",
        "string_choice": {
          "choices": ["eo://video/1", "eo://video/2", "eo://video/3"],
          "strict": true
        }
      }
    },
    "speaker": {
      "type": "STRUCT",
      "params": {
        "volume": {
          "type": "FLOAT32",
          "name": { "display_strings": { "en": "Volume a" } },
          "value": {"float32_value": 0.5}
        },
        "state": {
          "type": "STRING",
          "name": { "display_strings": { "en": "State a" } },
          "value": { "string_value": "on" },
          "constraint": {
            "type": "STRING_CHOICE",
            "string_choice": {
              "choices": ["on", "off"],
              "strict": true
            }
          }
        }
      }
    },
    "speakers": {
      "name": {"display_strings": {"en": "Speakers a"}},
      "type": "STRUCT_ARRAY",
      "template_oid": "/speaker",
      "value": {
        "struct_array_values": {
          "struct_values": [
            {
              "struct_value" : {
                "name": {"display_strings": {"en": "Speaker 1a"}},
                "fields": {
                  "volume": {"value": {"float32_value": 0.5}},
                  "state": {"value": {"string_value": "on"}}
                }
              }
            },
            {
              "struct_value" : {
                "name": {"display_strings": {"en": "Speaker 2a"}},
                "fields": {
                  "volume": {"value": {"float32_value": 1}},
                  "state": {"value": {"string_value": "off"}}
                }
              }
            }
          ]
        }
      }
    }
  },

  "commands": {
    "play": {
      "type":"EMPTY"
    },
    "pause": {
      "type":"EMPTY"
    },
    "stop": {
      "type":"EMPTY"
    },
    "rewind": {
      "type": "EMPTY"
    },
    "fast_forward": {
      "type": "EMPTY"
    },
    "load": {
      "type":"STRING"
    }
  }
}

=== rossvideo/Catena/sdks/cpp/connections/REST/examples/status_update_JSON_REST/device.status_update.json
{
  "slot": 1,
  "multi_set_enabled": true,
  "detail_level": "FULL",
  "access_scopes": ["st2138:mon", "st2138:op", "st2138:cfg", "st2138:adm"],
  "default_scope": "st2138:op",
  "subscriptions": true,
  "language_packs": {
    "packs": {
      "es": {
        "name": "Spanish",
        "words": {
          "greeting": "Hola",
          "parting": "Adiós"
        }
      },
      "en": {
        "name": "English",
        "words": {
          "greeting": "Hello",
          "parting": "Goodbye"
        }
      },
      "fr": {
        "name": "French",
        "words": {
          "greeting": "Bonjour",
          "parting": "Adieu"
        }
      }
    }
  },
  "params": {
    "counter": {
      "type": "INT32",
      "name": { "display_strings": { "en": "Counter", "es": "Contador", "fr": "Compteur" } },
      "value": { "int32_value": 0 },
      "minimal_set": true
    },
    "text_box": {
      "type": "STRING",
      "name": { "display_strings": { "en": "Text Box", "es": "Caja de Texto", "fr": "Boîte de Texte" } },
      "access_scope": "st2138:cfg",
      "value": { "string_value": "Hello, World!" }
    },
    "button": {
      "type": "INT32",
      "name": { "display_strings": { "en": "Button", "es": "Botón", "fr": "Bouton" } },
      "value": { "int32_value": 0 },
      "widget": "button",
      "constraint": { "ref_oid": "basic_button" }
    },
    "slider": {
      "type": "INT32",
      "name": { "display_strings": { "en": "Slider", "es": "Deslizador", "fr": "Curseur" } },
      "access_scope": "st2138:cfg",
      "value": { "int32_value": 0 },
      "constraint": { "ref_oid": "basic_slider" }
    },
    "combo_box": {
      "type": "INT32",
      "name": { "display_strings": { "en": "Combo Box", "es": "Caja Combinada", "fr": "Boîte Combo" } },
      "access_scope": "st2138:cfg",
      "value": { "int32_value": 1 },
      "constraint": {
        "type": "INT_CHOICE",
        "int32_choice": {
          "choices": [
            {
              "name": { "display_strings": { "en": "Choice 1", "es": "Opción 1", "fr": "Choix 1" } },
              "value": 1
            },
            {
              "name": { "display_strings": { "en": "Choice 2", "es": "Opción 2", "fr": "Choix 2" } },
              "value": 2
            },
            {
              "name": { "display_strings": { "en": "Choice 3", "es": "Opción 3", "fr": "Choix 3" } },
              "value": 3
            }
          ]
        }
      }
    },
    "dashboard_UI": {
      "type": "STRING",
      "oid_aliases": ["0xFF0E"],
      "read_only": true,
      "value": { "string_value": "eo://status_update.grid" }
    },
    "product": {
      "type": "STRUCT",
      "read_only": true,
      "value": {
        "struct_value": {
          "fields": {
            "name": { "string_value": "Status Update" },
            "vendor": { "string_value": "Ross Video" },
            "version": { "string_value": "1.0.0" },
            "catena_sdk": { "string_value": "https://github.com/rossvideo/Catena.git" },
            "serial_number": { "string_value": "SN-7K9M-2024-XR485-BLU" }
          }
        }
      },
      "params": {
        "name": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "vendor": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "version": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "catena_sdk": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "catena_sdk_version": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        },
        "serial_number": {
          "type": "STRING",
          "access_scope": "st2138:mon"
        }
      }
    }
  },
  "constraints": {
    "basic_button": {
      "type": "INT_CHOICE",
      "int32_choice": {
        "choices": [
          {
            "name": { "display_strings": { "en": "Off", "es": "Apagado", "fr": "Éteint" } },
            "value": 0
          },
          {
            "name": { "display_strings": { "en": "On", "es": "Encendido", "fr": "Allumé" } },
            "value": 1
          }
        ]
      }
    },
    "basic_slider": {
      "type": "INT_RANGE",
      "int32_range": {
        "min_value": -10,
        "max_value": 10,
        "step": 1
      }
    }
  }
}
