=== rossvideo/Catena/schema/catena.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Catena Device Model Schema",
  "description": "Intended to assist humans to author Catena device models as JSON files as some IDEs can use schemata such as this one to lint models.",
  "type": "object",
  "properties": {
    "oid": {
      "$ref": "#/$defs/oid"
    },
    "slot": {
      "$ref": "#/$defs/slot"
    },
    "detail_level": {
      "$ref": "#/$defs/detail_level"
    },
    "multi_set_enabled": {
      "title": "Multi Set Message Enabled Flag",
      "description": "Enables use of the multi-value message to report multiple parameter changes in one message. Otherwise changes will be reported individually using the value message. Defaults to true.",
      "type": "boolean"
    },
    "subscriptions": {
      "title": "Subscriptions Flag",
      "description": "When true, indicates that the device supports subscription-based access to subsets of parameters.",
      "type": "boolean"
    },
    "timeout": {
      "title": "Timeout",
      "description": "Time, in ms, after which device will timeout",
      "$comment": "get help with the description",
      "type": "integer",
      "min": 0,
      "max": 1000000
    },
    "params": {
      "$ref": "#/$defs/param_map"
    },
    "commands": {
      "$ref": "#/$defs/param_map"
    },
    "access_scopes": {
      "title": "Access Scopes",
      "description": "The access scopes recognised by this device",
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true,
        "maxItems": 5,
        "$comment": "discussion needed on min & max items"
      },
      "additionalItems": false
    },
    "default_scope": {
      "$id": "Default Access Scope",
      "description": "Objects in the model will have this access scope unless overridden explicitly, or implicitly by inheritance",
      "type": "integer",
      "minimum": 0,
      "maximum": 4
    }
  },
  "required": [
    "slot"
  ],
  "additionalProperties": false,
  "$defs": {
    "param_map": {
      "title": "map of params used for top-level params and commands objects",
      "description": "Defines the collection of parameter and command descriptors for a device, or a subset if the payload of a 'params' message.",
      "type": "object",
      "$comment": "patternProperties regex must be same as that defined in oid schema",
      "patternProperties": {
        "(^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$)": {
          "oneOf": [
            {
              "type": "object",
              "properties": {
                "import": {
                  "$ref": "#/$defs/import"
                }
              },
              "additionalProperties": false,
              "required": [
                "import"
              ]
            },
            {
              "type": "object",
              "properties": {
                "param": {
                  "$ref": "#/$defs/param"
                }
              },
              "additionalProperties": false,
              "required": [
                "param"
              ]
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "param": {
      "title": "Parameter Descriptor",
      "description": "Defines the type, value, constraints, UI, access modes and configuration options of a parameter.",
      "type": "object",
      "properties": {
        "fqoid": {
          "title": "Fully Qualified Object ID",
          "description": "JSON pointer to this parameter descriptor, relative to the top-level /params object",
          "type": "string",
          "format": "json-pointer"
        },
        "type": {
          "$ref": "#/$defs/type"
        },
        "value": {
          "$ref": "#/$defs/value"
        },
        "name": {
          "$ref": "#/$defs/polyglot_text"
        },
        "constraint": {
          "$ref": "#/$defs/constraint"
        },
        "params": {
          "$ref": "#/$defs/param_map"
        },
        "commands": {
          "$ref": "#/$defs/param_map"
        },
        "access_scope": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "type"
      ],
      "allOf": [
        {
          "$ref": "#/$defs/apply_float32"
        },
        {
          "$ref": "#/$defs/apply_int32"
        },
        {
          "$ref": "#/$defs/apply_struct"
        },
        {
          "$ref": "#/$defs/apply_int32_array"
        }
      ]
    },
    "value": {
      "title": "Parameter value",
      "description": "Value of the parameter. Its schema is polymorphic dependent on type."
    },
    "float32": {
      "type": "number",
      "minimum": -3.402823466385e38,
      "maximum": 3.402823466385e38,
      "default": 0
    },
    "float32_value": {
      "title": "FLOAT32",
      "description": "Defines FLOAT32 as a primitive number type",
      "type": "object",
      "properties": {
        "float32_value": {
          "$ref": "#/$defs/float32"
        }
      },
      "required": [
        "float32_value"
      ]
    },
    "float32_constraint": {
      "title": "Float32 Constraint",
      "description": "Range constraint with step size and display min/max",
      "type": "object",
      "properties": {
        "type": {
          "const": "FLOAT_RANGE"
        },
        "float_range": {
          "type": "object",
          "properties": {
            "min_value": {
              "$ref": "#/$defs/float32"
            },
            "max_value": {
              "$ref": "#/$defs/float32"
            },
            "step": {
              "$ref": "#/$defs/float32"
            },
            "display_min": {
              "$ref": "#/$defs/float32"
            },
            "display_max": {
              "$ref": "#/$defs/float32"
            }
          },
          "required": [
            "min_value",
            "max_value"
          ],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "apply_float32": {
      "title": "FLOAT32 specialism",
      "description": "Applies FLOAT32 values & constraints, disables properties that don't work with FLOAT32",
      "if": {
        "properties": {
          "type": {
            "properties": {
              "type": {
                "const": "FLOAT32"
              }
            }
          }
        }
      },
      "then": {
        "properties": {
          "value": {
            "$ref": "#/$defs/float32_value"
          },
          "constraint": {
            "$ref": "#/$defs/float32_constraint"
          }
        }
      }
    },
    "int32": {
      "type": "integer",
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "int32_value": {
      "title": "INT32",
      "description": "Defines INT32 as a primitive number type",
      "type": "object",
      "properties": {
        "int32_value": {
          "$ref": "#/$defs/int32"
        }
      },
      "required": [
        "int32_value"
      ],
      "additionalProperties": false
    },
    "int32_constraint": {
      "title": "INT32 Constraint",
      "description": "Range constraint with step size and display min/max",
      "type": "object",
      "properties": {
        "type": {
          "title": "INT32 Constraint types",
          "description": "Constraints for integers and integer arrays",
          "type": "string",
          "enum": [
            "INT_CHOICE",
            "INT_RANGE",
            "ALARM_TABLE"
          ]
        }
      },
      "required": [
        "type"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "INT_RANGE"
              }
            }
          },
          "then": {
            "properties": {
              "type": {
                "const": "INT_RANGE"
              },
              "int32_range": {
                "type": "object",
                "properties": {
                  "min_value": {
                    "$ref": "#/$defs/int32"
                  },
                  "max_value": {
                    "$ref": "#/$defs/int32"
                  },
                  "step": {
                    "$ref": "#/$defs/int32"
                  },
                  "display_min": {
                    "$ref": "#/$defs/int32"
                  },
                  "display_max": {
                    "$ref": "#/$defs/int32"
                  }
                },
                "required": [
                  "min_value",
                  "max_value"
                ],
                "additionalProperties": false
              }
            },
            "additionalProperties": false
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "INT_CHOICE"
              }
            }
          },
          "then": {
            "properties": {
              "type": {
                "const": "INT_CHOICE"
              },
              "int32_choice": {
                "type": "object",
                "properties": {
                  "choices": {
                    "type": "array",
                    "items": {
                      "$ref": "#/$defs/int_choice"
                    }
                  }
                },
                "required": [
                  "choices"
                ],
                "additionalProperties": false
              }
            },
            "additionalProperties": false
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "ALARM_TABLE"
              }
            }
          },
          "then": {
            "properties": {
              "type": {
                "const": "ALARM_TABLE"
              },
              "alarm_table": {
                "type": "object",
                "properties": {
                  "alarm_table": {
                    "type": "array",
                    "items": {
                      "$ref": "#/$defs/alarm"
                    },
                    "maxItems": 32
                  }
                },
                "additionalProperties": false
              }
            },
            "additionalProperties": false
          }
        }
      ]
    },
    "int_choice": {
      "title": "int choice constraint",
      "description": "maps strings intended for display in client to integers",
      "type": "object",
      "properties": {
        "value": {
          "$ref": "#/$defs/int32"
        },
        "name": {
          "$ref": "#/$defs/polyglot_text"
        }
      },
      "required": [
        "value",
        "name"
      ],
      "additionalProperties": false
    },
    "alarm": {
      "title": "Alarm",
      "description": "Occupies a bit position in an alarm table",
      "type": "object",
      "properties": {
        "bit_value": {
          "type": "integer",
          "minimum": 0,
          "maximum": 31
        },
        "severity": {
          "type": "string",
          "enum": [
            "INFO",
            "WARNING",
            "SEVERE",
            "UNKNOWN",
            "REFUSED"
          ]
        },
        "description": {
          "$ref": "#/$defs/polyglot_text"
        }
      },
      "required": [
        "bit_value",
        "severity",
        "description"
      ],
      "additionalProperties": false
    },
    "apply_int32": {
      "title": "INT32 specialism",
      "description": "Applies INT32 values & constraints, disables properties that don't work with this type",
      "if": {
        "properties": {
          "type": {
            "properties": {
              "type": {
                "const": "INT32"
              }
            }
          }
        }
      },
      "then": {
        "properties": {
          "value": {
            "$ref": "#/$defs/int32_value"
          },
          "constraint": {
            "$ref": "#/$defs/int32_constraint"
          }
        }
      }
    },
    "int32_array_values": {
      "title": "INT32_ARRAY",
      "description": "Defines INT32 array as a type",
      "type": "object",
      "properties": {
        "int32_array_values": {
          "type": "object",
          "properties": {
            "ints": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/int32"
              }
            },
            "additionalItems": false
          },
          "required": [
            "ints"
          ],
          "additionalProperties": false
        },
        "required": [
          "int32_array_values"
        ],
        "additionalProperties": false
      },
      "required": [
        "int32_array_values"
      ],
      "additionalProperties": false
    },
    "apply_int32_array": {
      "title": "INT32 ARRAY specialism",
      "description": "Applies INT32 ARRAY values & constraints, disables properties that don't work with this type",
      "if": {
        "properties": {
          "type": {
            "properties": {
              "type": {
                "const": "INT32_ARRAY"
              }
            }
          }
        }
      },
      "then": {
        "properties": {
          "value": {
            "$ref": "#/$defs/int32_array_values"
          },
          "constraint": {
            "$ref": "#/$defs/int32_constraint"
          }
        }
      }
    },
    "struct_value": {
      "title": "STRUCT",
      "description": "Wrapper round the struct_fields schema.",
      "type": "object",
      "$comment": "pattern properties must be same regex as for oid",
      "properties": {
        "struct_value": {
          "type": "object",
          "properties": {
            "fields": {
              "$ref": "#/$defs/struct_fields"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "struct_fields": {
      "title": "struct definition",
      "description": "holds struct data fields",
      "type": "object",
      "patternProperties": {
        "(^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$)": {
          "oneOf": [
            {
              "$ref": "#/$defs/float32_value"
            },
            {
              "$ref": "#/$defs/int32_value"
            },
            {
              "$ref": "#/$defs/struct_value"
            }
          ]
        },
        "additionalProperties": false
      },
      "additionalProperties": false
    },
    "apply_struct": {
      "title": "STRUCT specialism",
      "description": "Applies STRUCT values & constraints, disables properties that don't work with this specialism",
      "if": {
        "properties": {
          "type": {
            "properties": {
              "type": {
                "const": "STRUCT"
              }
            }
          }
        }
      },
      "then": {
        "properties": {
          "value": {
            "$ref": "#/$defs/struct_value"
          }
        }
      }
    },
    "apply_float32_value": {
      "if": {
        "properties": {
          "value": {
            "$ref": "#/$defs/float32_value"
          }
        }
      },
      "then": true,
      "else": false
    },
    "apply_int32_value": {
      "if": {
        "properties": {
          "value": {
            "$ref": "#/$defs/int32_value"
          }
        }
      },
      "then": true,
      "else": false
    },
    "apply_struct_value": {
      "if": {
        "properties": {
          "value": {
            "struct_value": true
          }
        }
      },
      "then": {
        "properties": {
          "value": {
            "$ref": "#/$defs/struct_value"
          }
        }
      }
    },
    "import": {
      "title": "Import directive",
      "description": "Provides the ability to build device models from multiple files. If a URL is provided, the import will be attempted from there. When absent, the import will be a local file named <schema>.<oid>.json.",
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "excluding": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false
    },
    "slot": {
      "title": "Slot ID",
      "description": "Uniquely identifies the device within the scope of its Catena connection",
      "type": "integer",
      "minimum": 0,
      "maximum": 65535,
      "default": 0
    },
    "detail_level": {
      "title": "Level of Detail",
      "description": "The level of detail in device messages and parameter updates. 'full' indicates that all parameters are reported, 'minimal' that only the minimal set is, and 'subscription' reports the minimal set plus identified subscribed parameters.",
      "type": "string",
      "enum": [
        "FULL",
        "SUBSCRIPTIONS",
        "MINIMAL"
      ],
      "default": "FULL"
    },
    "basic_param_info": {
      "title": "Basic Param Info",
      "description": "Summary information about a parameter",
      "type": "object",
      "properties": {
        "oid": {
          "$ref": "#/$defs/oid"
        },
        "name": {
          "$ref": "#/$defs/polyglot_text"
        },
        "type": {
          "$ref": "#/$defs/type"
        }
      },
      "$comment": "not having oid as required is correct because this schema is used in 2 places - param which would be duplicative, and as a message payload where it's needed",
      "additionalProperties": false
    },
    "oid": {
      "title": "Object ID",
      "description": "An object ID unique within the device model scope",
      "type": "string",
      "pattern": "(^(?!_)(?!\\d)(?![\\w\\.]*\\.\\d+?$)[\\w\\.]+$)"
    },
    "polyglot_text": {
      "title": "Polyglot Text",
      "description": "Text that a client can display in one of multiple languages",
      "type": "object",
      "properties": {
        "monoglot": {
          "title": "Monoglot",
          "description": "Fallback for single-language devices",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "readonly": {
      "title": "Parameter access mode",
      "description": "If set true, parameter is read only",
      "type": "boolean",
      "default": false
    },
    "param_type": {
      "title": "Parameter's data type",
      "description": "The parameter's data type",
      "type": "string",
      "enum": [
        "UNDEFINED",
        "EMPTY",
        "INT32",
        "FLOAT32",
        "STRING",
        "STRUCT",
        "INT32_ARRAY",
        "FLOAT32_ARRAY",
        "STRING_ARRAY",
        "BINARY",
        "STRUCT_ARRAY",
        "DATA"
      ],
      "default": "UNDEFINED"
    },
    "type": {
      "title": "Parameter type",
      "description": "Could be defined in-line or by reference to another parameter",
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/$defs/param_type"
        }
      },
      "additionalProperties": false
    },
    "constraint": {
      "title": "Constraint to apply to parameter value",
      "description": "Constraints on how the value of the parameter can change. Its schema is polymorphic dependent on type",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "UNDEFINED",
            "INT_RANGE",
            "FLOAT_RANGE",
            "INT_CHOICE",
            "STRING_CHOICE",
            "STRING_STRING_CHOICE",
            "ALARM_TABLE"
          ],
          "default": "UNDEFINED"
        }
      },
      "required": [
        "type"
      ]
    }
  }
}

=== rossvideo/Catena/example_device_models/import1/device.import1.json
{
    "slot": 1,
    "multi_set_enabled": true,
    "timeout": 100,
    "detail_level": "MINIMAL",
    "params": {
        "hello": {
            "param": {
                "name": {
                    "monoglot": "example defined inline"
                },
                "type": {
                    "type": "FLOAT32"
                },
                "value": {
                    "float32_value": 12.3
                },
                "constraint": {
                    "type": "FLOAT_RANGE",
                    "float_range": {
                        "min_value": 0.0,
                        "max_value": 1.0
                    }
                }
            }
        },
        "world": {
            "import": {}
        },
        "string_examples": {
            "import": {}
        },
        "tape_transport": {
            "import": {
                "excluding": [
                    "/commands/eject",
                    "/commands/load"
                ]
            }
        }
    }
}
